using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace TableGoal
{
    public enum Country
    {
        Argentina,
        Australia,
        Austria,
        Belgium,
        Bolivia,
        Bosnia,
        Brazil,
        Bulgaria,
        Burkina_Faso,
        Cameroon,
        Canada,
        Chile,
        China,
        Colombia,
        Cote_dIvoire,
        Croatia,
        Cyprus,
        Czech_Republic,
        Denmark,
        Ecuador,
        Egypt,
        England,
        Finland,
        France,
        Germany,
        Ghana,
        Greece,
        Hong_Kong,
        Hungary,
        Iceland,
        India,
        Ireland,
        Italy,
        Japan,
        Latvia,
        Lithuania,
        Mexico,
        Netherlands,
        New_Zealand,
        Norway,
        Paraguay,
        Peru,
        Poland,
        Portugal,
        Romania,
        Russian_Federation,
        Serbia_and_Montenegro,
        Singapore,
        Slovakia,
        Slovenia,
        South_Africa,
        South_Korea,
        Spain,
        Sweden,
        Switzerland,
        Turkey,
        Uganda,
        Ukraine,
        Uruguay,
        USA,
        UNKNOWN
    }
    public class Countries
    {
        static string flagsFolder = "Flags";
        public static Dictionary<Country, string> pathToFlags = new Dictionary<Country, string>()
        {
            {Country.Argentina, String.Format("WC/{0}/{1}", flagsFolder, Country.Argentina.ToString())},
            {Country.Austria, String.Format("WC/{0}/{1}", flagsFolder, Country.Austria.ToString())},
            {Country.Australia, String.Format("WC/{0}/{1}", flagsFolder, Country.Australia.ToString())},
            {Country.Belgium, String.Format("WC/{0}/{1}", flagsFolder, Country.Belgium.ToString())},
            {Country.Bolivia, String.Format("WC/{0}/{1}", flagsFolder, Country.Bolivia.ToString())},
            {Country.Bosnia, String.Format("WC/{0}/{1}", flagsFolder, Country.Bosnia.ToString())},
            {Country.Brazil, String.Format("WC/{0}/{1}", flagsFolder, Country.Brazil.ToString())},
            {Country.Bulgaria, String.Format("WC/{0}/{1}", flagsFolder, Country.Bulgaria.ToString())},
            {Country.Burkina_Faso, String.Format("WC/{0}/{1}", flagsFolder, Country.Burkina_Faso.ToString())},
            {Country.Cameroon, String.Format("WC/{0}/{1}", flagsFolder, Country.Cameroon.ToString())},
            {Country.Canada, String.Format("WC/{0}/{1}", flagsFolder, Country.Canada.ToString())},
            {Country.Chile, String.Format("WC/{0}/{1}", flagsFolder, Country.Chile.ToString())},
            {Country.China, String.Format("WC/{0}/{1}", flagsFolder, Country.China.ToString())},
            {Country.Colombia, String.Format("WC/{0}/{1}", flagsFolder, Country.Colombia.ToString())},
            {Country.Cote_dIvoire, String.Format("WC/{0}/{1}", flagsFolder, Country.Cote_dIvoire.ToString())},
            {Country.Croatia, String.Format("WC/{0}/{1}", flagsFolder, Country.Croatia.ToString())},
            {Country.Cyprus, String.Format("WC/{0}/{1}", flagsFolder, Country.Cyprus.ToString())},
            {Country.Czech_Republic, String.Format("WC/{0}/{1}", flagsFolder, Country.Czech_Republic.ToString())},
            {Country.Denmark, String.Format("WC/{0}/{1}", flagsFolder, Country.Denmark.ToString())},
            {Country.Ecuador, String.Format("WC/{0}/{1}", flagsFolder, Country.Ecuador.ToString())},
            {Country.Egypt, String.Format("WC/{0}/{1}", flagsFolder, Country.Egypt.ToString())},
            {Country.England, String.Format("WC/{0}/{1}", flagsFolder, Country.England.ToString())},
            {Country.Finland, String.Format("WC/{0}/{1}", flagsFolder, Country.Finland.ToString())},
            {Country.France, String.Format("WC/{0}/{1}", flagsFolder, Country.France.ToString())},
            {Country.Germany, String.Format("WC/{0}/{1}", flagsFolder, Country.Germany.ToString())},
            {Country.Ghana, String.Format("WC/{0}/{1}", flagsFolder, Country.Ghana.ToString())},
            {Country.Greece, String.Format("WC/{0}/{1}", flagsFolder, Country.Greece.ToString())},
            {Country.Hong_Kong, String.Format("WC/{0}/{1}", flagsFolder, Country.Hong_Kong.ToString())},
            {Country.Hungary, String.Format("WC/{0}/{1}", flagsFolder, Country.Hungary.ToString())},
            {Country.Iceland, String.Format("WC/{0}/{1}", flagsFolder, Country.Iceland.ToString())},
            {Country.India, String.Format("WC/{0}/{1}", flagsFolder, Country.India.ToString())},
            {Country.Ireland, String.Format("WC/{0}/{1}", flagsFolder, Country.Ireland.ToString())},
            {Country.Italy, String.Format("WC/{0}/{1}", flagsFolder, Country.Italy.ToString())},
            {Country.Japan, String.Format("WC/{0}/{1}", flagsFolder, Country.Japan.ToString())},
            {Country.Latvia, String.Format("WC/{0}/{1}", flagsFolder, Country.Latvia.ToString())},
            {Country.Lithuania, String.Format("WC/{0}/{1}", flagsFolder, Country.Lithuania.ToString())},
            {Country.Mexico, String.Format("WC/{0}/{1}", flagsFolder, Country.Mexico.ToString())},
            {Country.Netherlands, String.Format("WC/{0}/{1}", flagsFolder, Country.Netherlands.ToString())},
            {Country.New_Zealand, String.Format("WC/{0}/{1}", flagsFolder, Country.New_Zealand.ToString())},
            {Country.Norway, String.Format("WC/{0}/{1}", flagsFolder, Country.Norway.ToString())},
            {Country.Paraguay, String.Format("WC/{0}/{1}", flagsFolder, Country.Paraguay.ToString())},
            {Country.Peru, String.Format("WC/{0}/{1}", flagsFolder, Country.Peru.ToString())},
            {Country.Poland, String.Format("WC/{0}/{1}", flagsFolder, Country.Poland.ToString())},
            {Country.Portugal, String.Format("WC/{0}/{1}", flagsFolder, Country.Portugal.ToString())},
            {Country.Romania, String.Format("WC/{0}/{1}", flagsFolder, Country.Romania.ToString())},
            {Country.Russian_Federation, String.Format("WC/{0}/{1}", flagsFolder, Country.Russian_Federation.ToString())},
            {Country.Serbia_and_Montenegro, String.Format("WC/{0}/{1}", flagsFolder, Country.Serbia_and_Montenegro.ToString())},
            {Country.Singapore, String.Format("WC/{0}/{1}", flagsFolder, Country.Singapore.ToString())},
            {Country.Slovakia, String.Format("WC/{0}/{1}", flagsFolder, Country.Slovakia.ToString())},
            {Country.Slovenia, String.Format("WC/{0}/{1}", flagsFolder, Country.Slovenia.ToString())},
            {Country.South_Africa, String.Format("WC/{0}/{1}", flagsFolder, Country.South_Africa.ToString())},
            {Country.South_Korea, String.Format("WC/{0}/{1}", flagsFolder, Country.South_Korea.ToString())},
            {Country.Spain, String.Format("WC/{0}/{1}", flagsFolder, Country.Spain.ToString())},
            {Country.Sweden, String.Format("WC/{0}/{1}", flagsFolder, Country.Sweden.ToString())},
            {Country.Switzerland, String.Format("WC/{0}/{1}", flagsFolder, Country.Switzerland.ToString())},
            {Country.Turkey, String.Format("WC/{0}/{1}", flagsFolder, Country.Turkey.ToString())},
            {Country.Uganda, String.Format("WC/{0}/{1}", flagsFolder, Country.Uganda.ToString())},
            {Country.Ukraine, String.Format("WC/{0}/{1}", flagsFolder, Country.Ukraine.ToString())},
            {Country.Uruguay, String.Format("WC/{0}/{1}", flagsFolder, Country.Uruguay.ToString())},
            {Country.USA, String.Format("WC/{0}/{1}", flagsFolder, Country.USA.ToString())},
        };

        public static Dictionary<Country, int> offensiveStats = new Dictionary<Country, int>()
        {
            {Country.Argentina, 90},
            {Country.Austria, 60},
            {Country.Australia, 63},
            {Country.Belgium, 70},
            {Country.Bolivia, 68},
            {Country.Bosnia, 72},
            {Country.Brazil, 92},
            {Country.Bulgaria, 50},
            {Country.Burkina_Faso, 58},
            {Country.Cameroon, 76},
            {Country.Canada, 53},
            {Country.Chile, 69},
            {Country.China, 48},
            {Country.Colombia, 72},
            {Country.Cote_dIvoire, 82},
            {Country.Croatia, 76},
            {Country.Cyprus, 40},
            {Country.Czech_Republic, 76},
            {Country.Denmark, 77},
            {Country.Ecuador, 64},
            {Country.Egypt, 55},
            {Country.England, 86},
            {Country.Finland, 43},
            {Country.France, 69},
            {Country.Germany, 90},
            {Country.Ghana, 69},
            {Country.Greece, 70},
            {Country.Hong_Kong, 34},
            {Country.Hungary, 52},
            {Country.Iceland, 42},
            {Country.India, 38},
            {Country.Ireland, 59},
            {Country.Italy, 74},
            {Country.Japan, 69},
            {Country.Latvia, 49},
            {Country.Lithuania, 60},
            {Country.Mexico, 68},
            {Country.Netherlands, 90},
            {Country.New_Zealand, 58},
            {Country.Norway, 63},
            {Country.Paraguay, 70},
            {Country.Peru, 64},
            {Country.Poland, 70},
            {Country.Portugal, 89},
            {Country.Romania, 39},
            {Country.Russian_Federation, 75},
            {Country.Serbia_and_Montenegro, 83},
            {Country.Singapore, 39},
            {Country.Slovakia, 70},
            {Country.Slovenia, 76},
            {Country.South_Africa, 74},
            {Country.South_Korea, 75},
            {Country.Spain, 96},
            {Country.Sweden, 76},
            {Country.Switzerland, 63},
            {Country.Turkey, 59},
            {Country.Uganda, 58},
            {Country.Ukraine, 74},
            {Country.Uruguay, 86},
            {Country.USA, 78},
            {Country.UNKNOWN, 0}
        };

        public static Dictionary<Country, int> defensiveStats = new Dictionary<Country, int>()
        {
            {Country.Argentina, 70},
            {Country.Austria, 60},
            {Country.Australia, 68},
            {Country.Belgium, 55},
            {Country.Bolivia, 61},
            {Country.Bosnia, 64},
            {Country.Brazil, 86},
            {Country.Bulgaria, 40},
            {Country.Burkina_Faso, 50},
            {Country.Cameroon, 63},
            {Country.Canada, 49},
            {Country.Chile, 53},
            {Country.China, 42},
            {Country.Colombia, 45},
            {Country.Cote_dIvoire, 68},
            {Country.Croatia, 70},
            {Country.Cyprus, 46},
            {Country.Czech_Republic, 79},
            {Country.Denmark, 48},
            {Country.Ecuador, 39},
            {Country.Egypt, 37},
            {Country.England, 81},
            {Country.Finland, 49},
            {Country.France, 69},
            {Country.Germany, 89},
            {Country.Ghana, 68},
            {Country.Greece, 72},
            {Country.Hong_Kong, 39},
            {Country.Hungary, 52},
            {Country.Iceland, 42},
            {Country.India, 32},
            {Country.Ireland, 51},
            {Country.Italy, 69},
            {Country.Japan, 42},
            {Country.Latvia, 41},
            {Country.Lithuania, 49},
            {Country.Mexico, 57},
            {Country.Netherlands, 73},
            {Country.New_Zealand, 55},
            {Country.Norway, 49},
            {Country.Paraguay, 52},
            {Country.Peru, 53},
            {Country.Poland, 66},
            {Country.Portugal, 76},
            {Country.Romania, 33},
            {Country.Russian_Federation, 69},
            {Country.Serbia_and_Montenegro, 70},
            {Country.Singapore, 39},
            {Country.Slovakia, 65},
            {Country.Slovenia, 71},
            {Country.South_Africa, 72},
            {Country.South_Korea, 76},
            {Country.Spain, 89},
            {Country.Sweden, 68},
            {Country.Switzerland, 49},
            {Country.Turkey, 55},
            {Country.Uganda, 63},
            {Country.Ukraine, 64},
            {Country.Uruguay, 75},
            {Country.USA, 71},
            {Country.UNKNOWN, 0}
        };

        public static Dictionary<Country, DifficultyLevel> countriesSkills = new Dictionary<Country, DifficultyLevel>()
        {
            {Country.Argentina, DifficultyLevel.HARD},
            {Country.Austria, DifficultyLevel.MEDIUM},
            {Country.Australia, DifficultyLevel.MEDIUM},
            {Country.Belgium, DifficultyLevel.MEDIUM},
            {Country.Bolivia, DifficultyLevel.EASY},
            {Country.Bosnia, DifficultyLevel.MEDIUM},
            {Country.Brazil, DifficultyLevel.HARD},
            {Country.Bulgaria, DifficultyLevel.EASY},
            {Country.Burkina_Faso, DifficultyLevel.EASY},
            {Country.Cameroon, DifficultyLevel.MEDIUM},
            {Country.Canada, DifficultyLevel.EASY},
            {Country.Chile, DifficultyLevel.HARD},
            {Country.China, DifficultyLevel.EASY},
            {Country.Colombia, DifficultyLevel.EASY},
            {Country.Cote_dIvoire, DifficultyLevel.HARD},
            {Country.Croatia, DifficultyLevel.HARD},
            {Country.Cyprus, DifficultyLevel.EASY},
            {Country.Czech_Republic, DifficultyLevel.MEDIUM},
            {Country.Denmark, DifficultyLevel.MEDIUM},
            {Country.Ecuador, DifficultyLevel.EASY},
            {Country.Egypt, DifficultyLevel.EASY},
            {Country.England, DifficultyLevel.HARD},
            {Country.Finland, DifficultyLevel.EASY},
            {Country.France, DifficultyLevel.HARD},
            {Country.Germany, DifficultyLevel.HARD},
            {Country.Ghana, DifficultyLevel.MEDIUM},
            {Country.Greece, DifficultyLevel.HARD},
            {Country.Hong_Kong, DifficultyLevel.EASY},
            {Country.Hungary, DifficultyLevel.MEDIUM},
            {Country.Iceland, DifficultyLevel.EASY},
            {Country.India, DifficultyLevel.EASY},
            {Country.Ireland, DifficultyLevel.MEDIUM},
            {Country.Italy, DifficultyLevel.HARD},
            {Country.Japan, DifficultyLevel.HARD},
            {Country.Latvia, DifficultyLevel.MEDIUM},
            {Country.Lithuania, DifficultyLevel.EASY},
            {Country.Mexico, DifficultyLevel.MEDIUM},
            {Country.Netherlands, DifficultyLevel.HARD},
            {Country.New_Zealand, DifficultyLevel.EASY},
            {Country.Norway, DifficultyLevel.MEDIUM},
            {Country.Paraguay, DifficultyLevel.MEDIUM},
            {Country.Peru, DifficultyLevel.EASY},
            {Country.Poland, DifficultyLevel.MEDIUM},
            {Country.Portugal, DifficultyLevel.HARD},
            {Country.Romania, DifficultyLevel.EASY},
            {Country.Russian_Federation, DifficultyLevel.HARD},
            {Country.Serbia_and_Montenegro, DifficultyLevel.HARD},
            {Country.Singapore, DifficultyLevel.EASY},
            {Country.Slovakia, DifficultyLevel.MEDIUM},
            {Country.Slovenia, DifficultyLevel.MEDIUM},
            {Country.South_Africa, DifficultyLevel.HARD},
            {Country.South_Korea, DifficultyLevel.MEDIUM},
            {Country.Spain, DifficultyLevel.HARD},
            {Country.Sweden, DifficultyLevel.MEDIUM},
            {Country.Switzerland, DifficultyLevel.MEDIUM},
            {Country.Turkey, DifficultyLevel.MEDIUM},
            {Country.Uganda, DifficultyLevel.MEDIUM},
            {Country.Ukraine, DifficultyLevel.MEDIUM},
            {Country.Uruguay, DifficultyLevel.HARD},
            {Country.USA, DifficultyLevel.MEDIUM},
            {Country.UNKNOWN, DifficultyLevel.EASY}
        };

        public static Country GetCountryFromTextureName(string textureName)
        {
            if (!pathToFlags.ContainsValue(textureName))
                return Country.UNKNOWN;
            var result = (from entry in pathToFlags
                         where entry.Value == textureName
                         select entry).ToDictionary(pair => pair.Key, pair => pair.Value);
            if (result.Count <= 0)
                return Country.UNKNOWN;
            return result.Keys.ElementAt(0);
        }
    }
}
